version: '3.9'
services:
  wiremock:
    image: din-docker.apro.nbnco.net.au/rodolpheche/wiremock
    volumes:
      - ./wiremock:/home/wiremock
    ports:
      - 8080:8080
    command:
      - --verbose